import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image"
import logo from "../../public/logo.png"

import { api } from "../utils/api";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className="flex items-center justify-center h-screen"
        >
          <div
            className="relative flex h-2/3 w-3/4"
          >
            <div
              className="w-1/2 flex justify-center items-center"
            >
              <text
                className="font-semibold text-3xl text-center leading-loose"
              >
                Welcome to RoomBros: Your onestop shop to find rooms wherever you go!
              </text>
            </div>
            <div
              className="w-full flex justify-center items-center"
            >
              <Image
                alt="roombros"
                src={logo}
                width="500"
                height="500"
                className="rounded-full"
              />
            </div>
            <div
              className="absolute bottom-0 flex w-full justify-center items-center p-4"
            >
              <button
                className="bg-red-200 w-56 rounded-md text-white h-10 transition hover:bg-red-100 focus:outline-none"
              >
                Get Started
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
